import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.jdatepicker.JDatePicker;

import javax.swing.*;
import java.awt.*;

public class Grupes {
	private JPanel panel1;
	private JTabbedPane tabbedPane1;
	private JComboBox combo_0_GrupesNr;
	private JTextField text_0_GrupesNr;
	private JButton button_0_PridetiNauja;
	private JButton button_0_Pervadinti;
	private JButton button_0_Istrinti;
	private JLabel label_0_Grupe;
	private JComboBox combo_1_Grupe;
	private JTable table_1;
	private JCheckBox check_2_Iki;
	private JCheckBox check_2_VisosGr;
	private JButton button_2_PDF;
	private JComboBox combo_2_Grupe;
	private JTable table_0;
	private JDatePicker date_1;
	private JLabel label_1_Data;
	private JLabel label_1_Grupe;
	private JDatePicker date_2_Data;
	private JLabel label_2_Data;
	private JTable table_2;
	private JDatePicker date_2_Iki;
	private JLabel label_2_Grupe;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		tabbedPane1 = new JTabbedPane();
		panel1.add(tabbedPane1, BorderLayout.CENTER);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new FormLayout("fill:60px:noGrow,left:4dlu:noGrow,fill:max(d;4px):grow,left:4dlu:noGrow,fill:max(d;4px):grow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:m:noGrow,left:4dlu:noGrow,fill:m:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:400px:noGrow"));
		tabbedPane1.addTab("Grupės", panel2);
		combo_0_GrupesNr = new JComboBox();
		final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
		defaultComboBoxModel1.addElement("1");
		defaultComboBoxModel1.addElement("2");
		defaultComboBoxModel1.addElement("3");
		defaultComboBoxModel1.addElement("4");
		defaultComboBoxModel1.addElement("5");
		combo_0_GrupesNr.setModel(defaultComboBoxModel1);
		CellConstraints cc = new CellConstraints();
		panel2.add(combo_0_GrupesNr, cc.xy(3, 1));
		text_0_GrupesNr = new JTextField();
		text_0_GrupesNr.setText("1");
		panel2.add(text_0_GrupesNr, cc.xy(5, 1));
		button_0_PridetiNauja = new JButton();
		button_0_PridetiNauja.setText("Pridėti naują");
		panel2.add(button_0_PridetiNauja, cc.xy(7, 1));
		button_0_Pervadinti = new JButton();
		button_0_Pervadinti.setText("Pervadinti");
		panel2.add(button_0_Pervadinti, cc.xy(9, 1));
		label_0_Grupe = new JLabel();
		label_0_Grupe.setText("Grupė");
		panel2.add(label_0_Grupe, cc.xy(1, 1));
		button_0_Istrinti = new JButton();
		button_0_Istrinti.setText("Ištrinti");
		panel2.add(button_0_Istrinti, cc.xy(11, 1));
		final JScrollPane scrollPane1 = new JScrollPane();
		panel2.add(scrollPane1, cc.xyw(1, 3, 11, CellConstraints.FILL, CellConstraints.FILL));
		table_0 = new JTable();
		scrollPane1.setViewportView(table_0);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new FormLayout("fill:60px:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:60px:noGrow,left:4dlu:noGrow,fill:max(d;4px):grow", "center:d:noGrow,top:4dlu:noGrow,center:400px:noGrow"));
		tabbedPane1.addTab("Lankomumo suvedimas", panel3);
		date_1 = new JDatePicker();
		date_1.setShowYearButtons(true);
		panel3.add(date_1, cc.xy(3, 1));
		label_1_Data = new JLabel();
		label_1_Data.setHorizontalAlignment(4);
		label_1_Data.setText("Data");
		panel3.add(label_1_Data, cc.xy(1, 1));
		label_1_Grupe = new JLabel();
		label_1_Grupe.setHorizontalAlignment(4);
		label_1_Grupe.setText("Grupė");
		panel3.add(label_1_Grupe, cc.xy(5, 1));
		combo_1_Grupe = new JComboBox();
		final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
		defaultComboBoxModel2.addElement("1");
		combo_1_Grupe.setModel(defaultComboBoxModel2);
		panel3.add(combo_1_Grupe, cc.xy(7, 1));
		final JScrollPane scrollPane2 = new JScrollPane();
		panel3.add(scrollPane2, cc.xyw(1, 3, 7, CellConstraints.FILL, CellConstraints.FILL));
		table_1 = new JTable();
		scrollPane2.setViewportView(table_1);
		final JPanel panel4 = new JPanel();
		panel4.setLayout(new FormLayout("fill:60px:noGrow,left:4dlu:noGrow,fill:p:grow,left:4dlu:noGrow,fill:p:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,fill:60px:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:365px:noGrow"));
		tabbedPane1.addTab("Lankomumo peržiūra", panel4);
		date_2_Data = new JDatePicker();
		date_2_Data.setShowYearButtons(true);
		panel4.add(date_2_Data, cc.xy(3, 1));
		label_2_Data = new JLabel();
		label_2_Data.setHorizontalAlignment(4);
		label_2_Data.setText("Data");
		panel4.add(label_2_Data, cc.xy(1, 1));
		final JScrollPane scrollPane3 = new JScrollPane();
		panel4.add(scrollPane3, cc.xyw(1, 5, 8, CellConstraints.FILL, CellConstraints.FILL));
		table_2 = new JTable();
		scrollPane3.setViewportView(table_2);
		date_2_Iki = new JDatePicker();
		panel4.add(date_2_Iki, cc.xy(3, 3));
		check_2_Iki = new JCheckBox();
		check_2_Iki.setHorizontalAlignment(4);
		check_2_Iki.setText("Iki");
		panel4.add(check_2_Iki, cc.xy(1, 3));
		check_2_VisosGr = new JCheckBox();
		check_2_VisosGr.setText("Visos");
		panel4.add(check_2_VisosGr, cc.xy(8, 1));
		button_2_PDF = new JButton();
		button_2_PDF.setText("PDF");
		panel4.add(button_2_PDF, cc.xy(8, 3));
		label_2_Grupe = new JLabel();
		label_2_Grupe.setText("Grupė ");
		panel4.add(label_2_Grupe, cc.xy(5, 1));
		combo_2_Grupe = new JComboBox();
		final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
		defaultComboBoxModel3.addElement("1.1");
		combo_2_Grupe.setModel(defaultComboBoxModel3);
		panel4.add(combo_2_Grupe, cc.xy(5, 3));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
